### ISSUE TITLE
package updates

### ISSUE THREAD

**Issue by jojorb** [GeekLaunch/nodejs-template-emails#1]
hi thank you for this nice video,
i did an install from scratch with yarn (and npm as well but not go well).
with yarn i've got 
```
  "dependencies": {
    "bluebird": "^3.5.1",
    "email-templates": "^3.1.0",
    "handlebars": "^4.0.11",
    "nodemailer": "^4.2.0"
  }
```
and when i get to the console.log test

```js
loadTemplate('welcome', users).then((results) => {
	console.log(JSON.stringify(results, null, 4));
});
```

here the error after a `node index.js cmd`

```
let template = new EmailTemplate(path.join(__dirname, 'templates', templateName));
                   ^

TypeError: EmailTemplate is not a constructor
    at loadTemplate (/my/path/to//index.js:34:20)
....
```

i used the same code with a git clone of your repo and it works very well tho!

edit: 
just went on email-templates github here the fix for the v3
https://github.com/niftylettuce/email-templates#v3-breaking-changes

**Comment by encody** [comment]
Thanks for the tip! I've updated the README here and the description on YouTube and I'll add a branch to this repo that contains `email-templates@3`-compatible code.
